## **ASSIGNMENT 1**

⃣1. Create & Reshape Magic
Task:
● Create an array from 1 to 12
● Convert it into a 3×4 matrix
● Print:
○ Shape
○ Number of elements
○ Data type

In [ ]:
import numpy as np

In [ ]:
arr1=np.arange(1,13)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr=arr1.reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.size

12

In [ ]:
arr.dtype

dtype('int64')

⃣2. Even Number Finder
Task:
● Create numbers from 1 to 20.
● Print only even numbers.
● Print how many even numbers are there.


In [ ]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr1=arr[arr%2==0]
arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr1.size

10

️3.Row Sum Challenge
Task:
● Create a 3×3 random integer matrix (values between 1–10).
● Print row sums.
● Print column sums
● Print total sum

In [ ]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [ ]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [ ]:
np.sum(arr)

np.int64(45)

4⃣ .Maximum Finder
Task:
● Create a 4×4 random matrix.
● Find the maximum value.
● Find its position (row, column).

In [ ]:
import numpy as np

A = np.random.randint(1, 10, (4, 4))

max_value = A.max()
position = np.unravel_index(A.argmax(), A.shape)

print(A)
print("Maximum value:", max_value)
print("Position:", position)

[[7 6 9 8]
 [6 6 3 4]
 [5 2 1 1]
 [7 2 2 3]]
Maximum value: 9
Position: (np.int64(0), np.int64(2))


5 .Replace Using Condition
Task:
● Create numbers from 1 to 15.
● Replace all numbers divisible by 3 with -1.

In [ ]:
arr = np.arange(1, 16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr[arr%3==0]=-1
arr

array([ 1,  2, -1,  4,  5, -1,  7,  8, -1, 10, 11, -1, 13, 14, -1])

6. Simple Matrix Operations
Task:
● Create two 3×3 random matrices.
● Add them.
● Multiply them element-wise.
● Multiply them using matrix multiplication.

In [ ]:
import numpy as np

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

print("Addition:\n", A + B)

print("Element-wise Multiplication:\n", A * B)

print("Matrix Multiplication:\n", A @ B)

Matrix A:
 [[7 5 4]
 [2 4 9]
 [4 5 4]]
Matrix B:
 [[8 3 7]
 [3 3 4]
 [1 1 7]]
Addition:
 [[15  8 11]
 [ 5  7 13]
 [ 5  6 11]]
Element-wise Multiplication:
 [[56 15 28]
 [ 6 12 36]
 [ 4  5 28]]
Matrix Multiplication:
 [[75 40 97]
 [37 27 93]
 [51 31 76]]


7⃣ Mini ML Style Question
Task:
Given:
X = np.array([[2, 3],
[4, 5],
[6, 7]])
Multiply each row by 10 without using loops.

In [ ]:
import numpy as np

X = np.array([[2, 3],
              [4, 5],
              [6, 7]])
output = X * 10

print(output)


[[20 30]
 [40 50]
 [60 70]]


8⃣ Filter Rows Based on Condition
Task:
● Create a 5×3 random matrix (values between 0–20).
● Print only rows where row sum > 30.

In [ ]:
import numpy as np

A = np.random.randint(0, 21, (5, 3))

print("Matrix:\n", A)

for row in A:
    if row.sum() > 30:
        print(row)

Matrix:
 [[ 2 16 15]
 [ 7 12 12]
 [ 5 14 16]
 [12 15 11]
 [ 0 18  5]]
[ 2 16 15]
[ 7 12 12]
[ 5 14 16]
[12 15 11]


9⃣ Reverse an Array
Task:
● Create numbers from 1 to 10.
● Reverse the array using slicing.

In [ ]:
import numpy as np

A = np.arange(1, 11)

print(A[::-1])

[10  9  8  7  6  5  4  3  2  1]


10.Simple Normalization
Task:
● Create a 3×3 random matrix.
● Divide each row by its row sum.

In [ ]:
import numpy as np

A = np.random.randint(1, 10, (3, 3))

row_sum = A.sum(axis=1, keepdims=True)

normalized = A / row_sum

print(normalized)

[[0.2    0.4    0.4   ]
 [0.3125 0.1875 0.5   ]
 [0.3125 0.25   0.4375]]


# BONUS

1. Swap first and last column of a matrix.


In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

A[:, [0, -1]] = A[:, [-1, 0]]

print(A)


[[3 2 1]
 [6 5 4]
 [9 8 7]]


2. Create a 4×4 identity matrix.


In [ ]:
np. ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

3. Create a 5×5 matrix filled with zeros except the border filled with 1.

In [ ]:
import numpy as np

A = np.zeros((5, 5), dtype=int)

A[0, :] = 1
A[-1, :] = 1
A[:, 0] = 1
A[:, -1] = 1

print(A)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
